FROM openjdk:19
ARG JAR_FILE=build/libs/Backend-Like-0.0.1-SNAPSHOT.jar
ARG MONGODB_URI=mongodb://localhost:27017
ARG APPLICATION_PORT=8084
ARG PRODUCT_URL=http://localhost:8081/product
ENV MONGODB_URI=$MONGODB_URI
ENV APPLICATION_PORT=$APPLICATION_PORT
ENV PRODUCT_URL=$PRODUCT_URL
EXPOSE 8084
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
