name: Comment on Dependabot PR
on:
  pull_request:
    branches:
      - '*'

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment on PR
        run: node .github/scripts/comment-on-pr.js ${{ github.event.pull_request.number }}
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
